my HW7..
TroianSergii/test pull request #11
Opened 2022-12-21 09:28 UTC by TroianSergii

Please check my HW 7
thanks!

2022-12-22 17:55 UTC, klymenok requested changes

2022-12-22 17:55 UTC, klymenok commented on test/07/HW7.py
> +        delete <name> - to delete record by name """)
This description shows the wrong way how to use your program. Please, change it according to the read implementation

2022-12-22 17:55 UTC, klymenok commented on test/07/HW7.py
> +        del phone_book[user_input2]
It is better to check if key exists before delete it, otherwise you will have an error for non-existing key

2022-12-22 20:06 UTC, TroianSergii commented on test/07/HW7.py
> +        delete <name> - to delete record by name """)
I corrected the comments, but I'm unsure if I understood your request.
Thanks!

2022-12-22 20:06 UTC, TroianSergii commented on test/07/HW7.py
> +        del phone_book[user_input2]
Corrected

2022-12-23 17:58 UTC, klymenok commented on test/07/HW7.py
> +        delete <name> - to delete record by name """)
I mean, when it is written `delete <name>` I try to use this command like `delete abonent1`, but your program says that there is no such command. Fix the description of your commands. It this particular case, fix this line to `delete - to delete contact by its name """)`

2022-12-23 17:59 UTC, klymenok requested changes

2022-12-23 17:59 UTC, klymenok commented on test/07/HW7.py
> +        show <name> - detailed information about contact by its name
Change description here as well, because your program doesn't work when I put `show abonent1`

2022-12-23 18:12 UTC, TroianSergii commented on test/07/HW7.py
> +        delete <name> - to delete record by name """)
Noted. Made changes
Please check again.
Thanks!

2022-12-23 18:15 UTC, klymenok approved these changes
Looks good!

2022-12-23 18:16 UTC, merged