Hw 04
TroianSergii/test pull request #6
Opened 2022-12-12 12:23 UTC by TroianSergii

Please review my HW4 after the amendments
Thanks!

2022-12-12 20:13 UTC, klymenok requested changes

2022-12-12 20:13 UTC, klymenok commented on HW4/HW4.py
> +input_users_text = input("Please enter the test:")
Leave only one of these two files

2022-12-12 20:13 UTC, klymenok commented on HW4/HW4.py
> +if input_users_text.isdigit() == True:
You can ignore == True part since, in the end it automatically compare it with `True`

2022-12-13 10:34 UTC, closed without merging

2022-12-13 10:34 UTC, TroianSergii commented
changes needed